# Generated by Django 3.2.3 on 2021-07-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=100)),
                ('contacts_ext', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('team', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('last_date', models.DateTimeField(blank=True, null=True)),
                ('email_id', models.EmailField(max_length=100)),
                ('titleof', models.CharField(max_length=100)),
            ],
        ),
    ]
